// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZHKKCAYNvyaz6kbMW4ZZWlPuk9fI23bI',
    appId: '1:280648755062:web:5988883012d61061757c57',
    messagingSenderId: '280648755062',
    projectId: 'lobbytalk-91e63',
    authDomain: 'lobbytalk-91e63.firebaseapp.com',
    storageBucket: 'lobbytalk-91e63.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoN4QYrPOl2w7IDL1s_YPCnb0Jcm3gaW0',
    appId: '1:280648755062:android:a424dd919caf0546757c57',
    messagingSenderId: '280648755062',
    projectId: 'lobbytalk-91e63',
    storageBucket: 'lobbytalk-91e63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoq9nqP-WgY62zPkMl4g4BYYcEzAAwAeY',
    appId: '1:280648755062:ios:dba969c09d001ade757c57',
    messagingSenderId: '280648755062',
    projectId: 'lobbytalk-91e63',
    storageBucket: 'lobbytalk-91e63.firebasestorage.app',
    iosBundleId: 'com.example.lobbytalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoq9nqP-WgY62zPkMl4g4BYYcEzAAwAeY',
    appId: '1:280648755062:ios:dba969c09d001ade757c57',
    messagingSenderId: '280648755062',
    projectId: 'lobbytalk-91e63',
    storageBucket: 'lobbytalk-91e63.firebasestorage.app',
    iosBundleId: 'com.example.lobbytalk',
  );
}
